name: Java CI with Maven  # Название процесса

on: [push]  # Запускать при каждом push в репозиторий

jobs:
  build:  # Задача "Сборка"
    runs-on: ubuntu-latest  # Используем виртуальную машину Ubuntu

    steps:
      # Шаг 1: Загружаем код из репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Версия OpenJDK

      # Шаг 3: Собираем проект с Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml